### ISSUE TITLE
Add support for Prosperity Second edition

### ISSUE THREAD

**Issue by gjedlicska** [GagaMen/dominionizer#8]
**Is your feature request related to a problem? Please describe.**
The second edition of the Prosperity expansion is missing from the generator.

**Describe the solution you'd like**
Add the new (reworked) expansion as an expansion select option.

**Additional context**
The cards of the second edition can be found [here](http://wiki.dominionstrategy.com/index.php/Prosperity#Kingdom_cards.2C_second_edition).

**Comment by TobiDimmel** [comment]
We currently work on a tool that extracts all expansion/card data from the wiki automatically.
I hope we can finish it and make the necessary adjustments to the app within the next weeks.

**Comment by GagaMen** [comment]
Hi @gjedlicska,

I have just released a new version, which includes all current expansions.

Have fun
